### ISSUE TITLE
Adapter headers "forEach not defined" 

### ISSUE THREAD

**Issue by blisst** [Zatvobor/ember-data-elasticsearch-kit#57]
When adding headers to the adapter, I get the error "forEach not defined."

The error is on line 53, and I would like to fix it I'm a newb and don't really know how to create pull requests...

If I'm not mistaken it should be 
    hash.beforeSend = function(xhr) {
        return Ember.keys(headers).forEach(function(key) {
            return xhr.setRequestHeader(key, headers[key]);
        });
    };

**Comment by Zatvobor** [comment]
I'll check this
